// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using big_isaac_project.Data;

#nullable disable

namespace big_isaac_project.Migrations
{
    [DbContext(typeof(CharacterContext))]
    partial class CharacterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("big_isaac_project.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Damage")
                        .HasColumnType("float");

                    b.Property<double>("Health")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Speed")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Damage = 2.0,
                            Health = 3.0,
                            Name = "Isaac",
                            Speed = 2.0
                        },
                        new
                        {
                            Id = 2,
                            Damage = 2.0,
                            Health = 4.0,
                            Name = "Magdalene",
                            Speed = 1.0
                        },
                        new
                        {
                            Id = 3,
                            Damage = 3.0,
                            Health = 2.0,
                            Name = "Cain",
                            Speed = 3.0
                        },
                        new
                        {
                            Id = 4,
                            Damage = 4.0,
                            Health = 1.0,
                            Name = "Judas",
                            Speed = 2.0
                        },
                        new
                        {
                            Id = 5,
                            Damage = 2.0,
                            Health = -1.0,
                            Name = "???",
                            Speed = 2.0
                        },
                        new
                        {
                            Id = 6,
                            Damage = 1.0,
                            Health = 2.0,
                            Name = "Eve",
                            Speed = 3.0
                        },
                        new
                        {
                            Id = 7,
                            Damage = 2.0,
                            Health = 3.0,
                            Name = "Samson",
                            Speed = 2.0
                        },
                        new
                        {
                            Id = 8,
                            Damage = 4.0,
                            Health = -1.0,
                            Name = "Azazel",
                            Speed = 3.0
                        },
                        new
                        {
                            Id = 9,
                            Damage = 2.0,
                            Health = 3.0,
                            Name = "Lazarus",
                            Speed = 2.0
                        },
                        new
                        {
                            Id = 10,
                            Damage = 0.0,
                            Health = 0.0,
                            Name = "Eden",
                            Speed = 0.0
                        },
                        new
                        {
                            Id = 11,
                            Damage = 2.0,
                            Health = 0.0,
                            Name = "The Lost",
                            Speed = 2.0
                        },
                        new
                        {
                            Id = 12,
                            Damage = 2.0,
                            Health = 1.0,
                            Name = "Lilith",
                            Speed = 2.0
                        },
                        new
                        {
                            Id = 13,
                            Damage = 2.0,
                            Health = 2.0,
                            Name = "Apollyon",
                            Speed = 2.0
                        },
                        new
                        {
                            Id = 14,
                            Damage = 4.0,
                            Health = -1.0,
                            Name = "The Forgotten",
                            Speed = 2.0
                        },
                        new
                        {
                            Id = 15,
                            Damage = 2.0,
                            Health = 3.0,
                            Name = "Bethany",
                            Speed = 2.0
                        },
                        new
                        {
                            Id = 16,
                            Damage = 3.0,
                            Health = 3.0,
                            Name = "Jacob & Esau",
                            Speed = 2.0
                        },
                        new
                        {
                            Id = 17,
                            Damage = 2.0,
                            Health = 3.0,
                            Name = "Tainted Isaac",
                            Speed = 2.0
                        },
                        new
                        {
                            Id = 18,
                            Damage = 1.0,
                            Health = 4.0,
                            Name = "Tainted Magdalene",
                            Speed = 2.0
                        },
                        new
                        {
                            Id = 19,
                            Damage = 2.0,
                            Health = 2.0,
                            Name = "Tainted Cain",
                            Speed = 3.0
                        },
                        new
                        {
                            Id = 20,
                            Damage = 2.0,
                            Health = -1.0,
                            Name = "Tainted Judas",
                            Speed = 3.0
                        },
                        new
                        {
                            Id = 21,
                            Damage = 1.0,
                            Health = -1.0,
                            Name = "Tainted ???",
                            Speed = 1.0
                        },
                        new
                        {
                            Id = 22,
                            Damage = 1.0,
                            Health = 2.0,
                            Name = "Tainted Eve",
                            Speed = 3.0
                        },
                        new
                        {
                            Id = 23,
                            Damage = 1.0,
                            Health = 3.0,
                            Name = "Tainted Samson",
                            Speed = 2.0
                        },
                        new
                        {
                            Id = 24,
                            Damage = 4.0,
                            Health = -1.0,
                            Name = "Tainted Azazel",
                            Speed = 2.0
                        },
                        new
                        {
                            Id = 25,
                            Damage = 2.0,
                            Health = 3.0,
                            Name = "Tainted Lazarus",
                            Speed = 2.0
                        },
                        new
                        {
                            Id = 26,
                            Damage = 0.0,
                            Health = 0.0,
                            Name = "Tainted Eden",
                            Speed = 0.0
                        },
                        new
                        {
                            Id = 27,
                            Damage = 3.0,
                            Health = 0.0,
                            Name = "Tainted Lost",
                            Speed = 2.0
                        },
                        new
                        {
                            Id = 28,
                            Damage = 2.0,
                            Health = 1.0,
                            Name = "Tainted Lilith",
                            Speed = 2.0
                        },
                        new
                        {
                            Id = 29,
                            Damage = 1.0,
                            Health = 2.0,
                            Name = "Tainted Apollyon",
                            Speed = 2.0
                        },
                        new
                        {
                            Id = 30,
                            Damage = 4.0,
                            Health = -1.0,
                            Name = "Tainted The Forgotten",
                            Speed = -1.0
                        },
                        new
                        {
                            Id = 31,
                            Damage = 2.0,
                            Health = -1.0,
                            Name = "Tainted Bethany",
                            Speed = 2.0
                        },
                        new
                        {
                            Id = 32,
                            Damage = 3.0,
                            Health = 3.0,
                            Name = "Tainted Jacob",
                            Speed = 2.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
